// <auto-generated />
namespace KatlaSport.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Reworked : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Reworked));
        
        string IMigrationMetadata.Id
        {
            get { return "201908051025506_Reworked"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
